### ISSUE TITLE
Add check if the BATCH_TCK_DIR has already been set and use the already set value.

### ISSUE THREAD

**Issue by scottmarlow** [jberet/jberet-tck-runner#9]
https://github.com/jberet/jberet-tck-runner/blob/main/run-tck.sh#L29 always will use the `2.1.1` Batch TCK currently.

**Comment by liweinan** [comment]
@scottmarlow With this manual action: https://github.com/jberet/jberet-tck-runner/blob/main/.github/workflows/manual.yml

The Batch TCK can be setup:

![33761713798666_ pic](https://github.com/jberet/jberet-tck-runner/assets/201907/df01fdcc-7215-456e-aa82-0fd1b53ae2c6)

And it's used during testing:

https://github.com/jberet/jberet-tck-runner/actions/runs/8786698923/job/24110149715#step:4:9

Is this an acceptable solution?

**Comment by scottmarlow** [comment]
Good idea, I will try that!

**Comment by scottmarlow** [comment]
@liweinan actually, I thought we were using jberet-tck-runner but I guess we are not.

**Comment by liweinan** [comment]
@scottmarlow Yes this project uses the `jberet-tck-porting` too to run the TCK tests periodically.
